### PR TITLE
fixes to joy_to_jog_joint.py

### PR DESCRIPTION
**Pull request by ghost**
Fixed the naming of the message
Made the joint names obtained from parameter

### CODE REVIEW

**Comment by jpsantos-motofil** [comment]
Added a node that is the integration of joy_to_jog_frame.py and joy_to_jog_joint.py.  It allows to switch from and to joint movement with the controller

**Comment by jpsantos-motofil** [comment]
To use it, just launch it exactly how you would launch joy_to_jog_frame.py

**Comment by 7675t** [comment]
Thanks, it is good idea to make the joint and frame jog into one joystick controller.
Can you append a simple usage section in jog_controllers README.md to reproduce and confirm your change?
And joint_name seems not parsed correctly. I think we can use /jog_joint_node/joint_names for joint name list.

**Comment by ghost** [comment]
The README.md does not need any change, the process is exactly the same, joypad.launch just needed a little fix https://github.com/tork-a/jog_control/pull/44/commits/e80677dc6fdb109452058c57de06b80e5f0b3c66
Also already changed the topic https://github.com/tork-a/jog_control/pull/44/commits/ddc95e4933875b6fb748484625d3e81007e97581

**Pull request closed without merging**
